development:
  adapter: mysql2
  encoding: utf8mb4
  database: meatme_development
  host: localhost
  username: root
  password: ilovecharlie1329

test:
  adapter: mysql2
  encoding: utf8mb4
  database: meatme_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8mb4
  database: meatme
  host: localhost
  username: root
  password:
